version: "3"
services:
  python:
    container_name: python
    build:
      context: .
      dockerfile:  ./Dockerfile
    volumes:
      - ./key:/usr/local/key
      - ./src:/usr/local/src
    ports:
      - "40022:22"
